org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.parallel=true

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3g
kotlin.native.ignoreDisabledTargets=true

android.useAndroidX=true
android.nonTransitiveRClass=true

GROUP=in.sitharaj.kova
VERSION_NAME=0.1.0

POM_NAME=Kova
POM_DESCRIPTION=Production-ready Kotlin Multiplatform MVVM library with first-class Swift interop: native flows, shared ViewModels, one-shot events, and KSP-generated Swift-friendly APIs.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/sitharaj88/kova
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/sitharaj88/kova
POM_SCM_CONNECTION=scm:git:git://github.com/sitharaj88/kova.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/sitharaj88/kova.git
POM_DEVELOPER_ID=sitharaj88
POM_DEVELOPER_NAME=Sitharaj Seenivasan
POM_DEVELOPER_URL=https://github.com/sitharaj88
