package sitharaj.kova.ksp

import com.google.devtools.ksp.getVisibility
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.Visibility
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo

private const val NATIVE_EXPORT = "sitharaj.kova.annotations.NativeExport"
private const val VIEW_MODEL = "androidx.lifecycle.ViewModel"

private val NATIVE_FLOW = ClassName("sitharaj.kova.core", "NativeFlow")
private val NATIVE_STATE_FLOW = ClassName("sitharaj.kova.core", "NativeStateFlow")

/** Flow-like types that expose a synchronous `value` and map to [NATIVE_STATE_FLOW]. */
private val STATE_FLOW_TYPES = setOf(
    "kotlinx.coroutines.flow.StateFlow",
    "kotlinx.coroutines.flow.MutableStateFlow",
)

/** Flow-like types that map to [NATIVE_FLOW]. */
private val FLOW_TYPES = setOf(
    "kotlinx.coroutines.flow.Flow",
    "kotlinx.coroutines.flow.SharedFlow",
    "kotlinx.coroutines.flow.MutableSharedFlow",
    "sitharaj.kova.core.EventFlow",
    "sitharaj.kova.core.MutableEventFlow",
)

public class NativeExportProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        NativeExportProcessor(environment.codeGenerator, environment.logger)
}

/**
 * Generates Swift-friendly `<property>Native` extension properties for every public
 * `StateFlow`/`Flow`/`EventFlow` property of classes annotated with `@NativeExport`.
 */
public class NativeExportProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(NATIVE_EXPORT)
        val deferred = symbols.filter { !it.validate() }.toList()

        symbols
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.validate() }
            .forEach { processClass(it) }

        return deferred
    }

    private fun processClass(declaration: KSClassDeclaration) {
        val className = declaration.toClassName()

        if (!declaration.extendsViewModel()) {
            logger.error(
                "@NativeExport requires ${className.simpleName} to extend $VIEW_MODEL " +
                    "(e.g. StateViewModel).",
                declaration,
            )
            return
        }
        if (declaration.typeParameters.isNotEmpty()) {
            logger.error(
                "@NativeExport does not support generic classes: ${className.simpleName}.",
                declaration,
            )
            return
        }

        val properties = declaration.getAllProperties()
            .filter { it.getVisibility() == Visibility.PUBLIC }
            .mapNotNull { property -> flowProperty(property) }
            .toList()

        if (properties.isEmpty()) {
            logger.warn(
                "@NativeExport on ${className.simpleName} found no public " +
                    "StateFlow/Flow/EventFlow properties.",
                declaration,
            )
            return
        }

        val file = FileSpec.builder(className.packageName, "${className.simpleName}Native")
            .addFileComment("Generated by Kova. Do not edit.")
            .addImport("androidx.lifecycle", "viewModelScope")
            .addImport("sitharaj.kova.core", "asNative")
            .apply { properties.forEach { addProperty(it) } }
            .build()

        file.writeTo(
            codeGenerator,
            Dependencies(aggregating = false, declaration.containingFile!!),
        )
    }

    private fun flowProperty(property: KSPropertyDeclaration): PropertySpec? {
        val type: KSType = property.type.resolve()
        val qualifiedName = type.declaration.qualifiedName?.asString() ?: return null

        val wrapper = when (qualifiedName) {
            in STATE_FLOW_TYPES -> NATIVE_STATE_FLOW
            in FLOW_TYPES -> NATIVE_FLOW
            else -> return null
        }

        val valueType = type.arguments.firstOrNull()?.type?.resolve() ?: return null
        if (valueType.isMarkedNullable) {
            logger.warn(
                "Skipping ${property.simpleName.asString()}: nullable flow value types are " +
                    "not representable in Objective-C generics. Model absence inside your " +
                    "state class instead.",
                property,
            )
            return null
        }

        val name = property.simpleName.asString()
        return PropertySpec.builder("${name}Native", wrapper.parameterizedBy(valueType.toTypeName()))
            .receiver((property.parentDeclaration as KSClassDeclaration).toClassName())
            .getter(
                FunSpec.getterBuilder()
                    .addStatement("return %L.asNative(viewModelScope)", name)
                    .build(),
            )
            .addKdoc("Swift-friendly view of [%L]. Emissions arrive on the main thread.", name)
            .build()
    }

    private fun KSClassDeclaration.extendsViewModel(): Boolean =
        superTypes.any { superType ->
            val decl = superType.resolve().declaration as? KSClassDeclaration ?: return@any false
            decl.qualifiedName?.asString() == VIEW_MODEL || decl.extendsViewModel()
        }
}
